version: '3.1'

services:

  db:
    image: mariadb
    container_name: mariadb-transportador
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3308:3306"
    volumes:
    - spring_data:/var/lib/mysql
    mem_limit: 1024m

volumes:
  spring_data: